version: '3'
services:
    

  postgres:
    restart: always
    image: postgres:10
    volumes:
      - ../postgresql-data:/var/lib/postgresql/data
      - ./postgresql-init:/docker-entrypoint-initdb.d
    environment:
      - PGDATA=/var/lib/postgresql/data/10
      - POSTGRES_USER=postgres
    ports:
      - "127:0.0.1:5432:5432"

  django:
    restart: always
    build:
      context: .
      dockerfile: ./compose/django/DockerFile
    command: python manage.py runserver 0.0.0.0:8000
    image: django-dev
    volumes:
      - .:/site
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - postgres
