CREATE USER dbmanager WITH ENCRYPTED PASSWORD 'dbmanager';
ALTER USER dbmanager CREATEDB;
CREATE DATABASE library OWNER dbmanager ENCODING 'UTF-8';
GRANT ALL PRIVILEGES ON DATABASE library TO dbmanager;